'use client'

import React, { useState } from 'react'
import { Plus } from 'lucide-react'
import { Button } from "@/components/ui/button"
import { motion, AnimatePresence } from 'framer-motion'

interface FAQItem {
  question: string
  answer: string
}

const faqData: FAQItem[] = [
  {
    question: "What is v0?",
    answer: "v0 is an AI-powered development tool that helps you build and deploy web applications quickly and efficiently."
  },
  {
    question: "How does v0 work?",
    answer: "v0 uses advanced AI algorithms to understand your requirements and generate code, designs, and other assets based on your input. It can create entire web applications or assist with specific components and features."
  },
  {
    question: "Is v0 suitable for beginners?",
    answer: "Yes, v0 is designed to be user-friendly and accessible to developers of all skill levels, including beginners. It provides guidance and explanations along with the generated code."
  },
  {
    question: "Can I customize the code generated by v0?",
    answer: "The code generated by v0 is fully customizable. You can modify, extend, or refactor it to suit your specific needs and preferences."
  },
  {
    question: "What technologies does v0 support?",
    answer: "v0 supports a wide range of modern web technologies, including but not limited to React, Next.js, Tailwind CSS, and various other popular frameworks and libraries."
  }
]

const FAQSection: React.FC = () => {
  const [openItems, setOpenItems] = useState<number[]>([])

  const toggleItem = (index: number) => {
    setOpenItems(prevOpenItems =>
      prevOpenItems.includes(index)
        ? prevOpenItems.filter(item => item !== index)
        : [...prevOpenItems, index]
    )
  }

  return (
    <section className="bg-white py-24">
      <div className="container mx-auto px-4 max-w-[1140px]">
        <h2 className="text-3xl font-bold text-center mb-12">Frequently Asked Questions</h2>
        <div className="space-y-4 max-w-[800px] mx-auto">
          {faqData.map((item, index) => (
            <div key={index} className="border border-gray-200 rounded-lg overflow-hidden">
              <Button
                variant="ghost"
                className="w-full flex justify-between items-center p-4 text-left"
                onClick={() => toggleItem(index)}
              >
                <span className="font-medium">{item.question}</span>
                <motion.div
                  initial={false}
                  animate={{ rotate: openItems.includes(index) ? 45 : 0 }}
                  transition={{ duration: 0.3 }}
                >
                  <Plus className="h-5 w-5 flex-shrink-0" />
                </motion.div>
              </Button>
              <AnimatePresence initial={false}>
                {openItems.includes(index) && (
                  <motion.div
                    key={`content-${index}`}
                    initial="collapsed"
                    animate="open"
                    exit="collapsed"
                    variants={{
                      open: { opacity: 1, height: "auto" },
                      collapsed: { opacity: 0, height: 0 }
                    }}
                    transition={{ duration: 0.3, ease: [0.04, 0.62, 0.23, 0.98] }}
                  >
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      exit={{ opacity: 0 }}
                      transition={{ duration: 0.2 }}
                    >
                      <div className="px-4 pb-4">
                        <p className="text-gray-600">{item.answer}</p>
                      </div>
                    </motion.div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}

export default FAQSection

